import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Cairo } from "next/font/google";

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://alphaafin.com.au/wp-content/uploads/2024/08/2-e1723186410313-150x150.png"
          sizes="32x32"
        />
        <link
          rel="icon"
          href="https://alphaafin.com.au/wp-content/uploads/2024/08/2-1024x1024.png"
          sizes="192x192"
        />
        <link
          rel="apple-touch-icon"
          href="https://alphaafin.com.au/wp-content/uploads/2024/08/2-1024x1024.png"
        />
      </head>
      <body className={cairo.className}>{children}</body>
    </html>
  );
}
